# Part1

Step2: creat a dataframe\
As in China, wikipedia is blocked for access, I can only download it by using proxy service, and then use the local url for this html doc.

In [8]:
import pandas as pd

url = '/Users/aesth/Desktop/List of postal codes of Canada_ M - Wikipedia.html'
df = pd.read_html(url)
df = df[0]

df.head(10)

  Postal code           Borough                                  Neighborhood
0         M1A      Not assigned                                           NaN
1         M2A      Not assigned                                           NaN
2         M3A        North York                                     Parkwoods
3         M4A        North York                              Victoria Village
4         M5A  Downtown Toronto                    Regent Park / Harbourfront
5         M6A        North York             Lawrence Manor / Lawrence Heights
6         M7A  Downtown Toronto  Queen's Park / Ontario Provincial Government
7         M8A      Not assigned                                           NaN
8         M9A         Etobicoke                              Islington Avenue
9         M1B       Scarborough                               Malvern / Rouge

Step3: create valid dataframe

In [10]:
df=df[df.Borough != 'Not assigned']
df.head(10)

   Postal code           Borough                                  Neighborhood
2          M3A        North York                                     Parkwoods
3          M4A        North York                              Victoria Village
4          M5A  Downtown Toronto                    Regent Park / Harbourfront
5          M6A        North York             Lawrence Manor / Lawrence Heights
6          M7A  Downtown Toronto  Queen's Park / Ontario Provincial Government
8          M9A         Etobicoke                              Islington Avenue
9          M1B       Scarborough                               Malvern / Rouge
11         M3B        North York                                     Don Mills
12         M4B         East York              Parkview Hill / Woodbine Gardens
13         M5B  Downtown Toronto                      Garden District, Ryerson

In [24]:
df['Neighborhood'].replace('Not assigned', df['Borough'])
df['Neighborhood'].replace('NaN', df['Borough'])
df = df.replace({'/': ','}, regex=True)
df

,Postal code,Borough,Neighborhood
2,M3A,North York,Parkwoods
3,M4A,North York,Victoria Village
4,M5A,Downtown Toronto,"Regent Park , Harbourfront"
5,M6A,North York,"Lawrence Manor , Lawrence Heights"
6,M7A,Downtown Toronto,"Queen's Park , Ontario Provincial Government"
...,...,...,...
160,M8X,Etobicoke,"The Kingsway , Montgomery Road , Old Mill North"
165,M4Y,Downtown Toronto,Church and Wellesley
168,M7Y,East Toronto,Business reply mail Processing CentrE
169,M8Y,Etobicoke,"Old Mill South , King's Mill Park , Sunnylea ,..."
178,M8Z,Etobicoke,"Mimico NW , The Queensway West , South of Bloo..."

In [25]:
df['Postal code'].drop_duplicates
df

,Postal code,Borough,Neighborhood
2,M3A,North York,Parkwoods
3,M4A,North York,Victoria Village
4,M5A,Downtown Toronto,"Regent Park , Harbourfront"
5,M6A,North York,"Lawrence Manor , Lawrence Heights"
6,M7A,Downtown Toronto,"Queen's Park , Ontario Provincial Government"
...,...,...,...
160,M8X,Etobicoke,"The Kingsway , Montgomery Road , Old Mill North"
165,M4Y,Downtown Toronto,Church and Wellesley
168,M7Y,East Toronto,Business reply mail Processing CentrE
169,M8Y,Etobicoke,"Old Mill South , King's Mill Park , Sunnylea ,..."
178,M8Z,Etobicoke,"Mimico NW , The Queensway West , South of Bloo..."

In [26]:
df.shape

(103, 3)

# Part 2

In [33]:
df_geo=pd.read_csv('D:\Chrome\download\Geospatial_Coordinates.csv')
df_geo

    Postal Code   Latitude  Longitude
0           M1B  43.806686 -79.194353
1           M1C  43.784535 -79.160497
2           M1E  43.763573 -79.188711
3           M1G  43.770992 -79.216917
4           M1H  43.773136 -79.239476
..          ...        ...        ...
98          M9N  43.706876 -79.518188
99          M9P  43.696319 -79.532242
100         M9R  43.688905 -79.554724
101         M9V  43.739416 -79.588437
102         M9W  43.706748 -79.594054

[103 rows x 3 columns]

In [36]:
import numpy as np

In [42]:
df_geo.rename(columns={'Postal Code': 'Postal code'}, inplace=True)
df_geo_merged = pd.merge(df, df_geo, on= 'Postal code')
df_geo_merged.head(10)

,Postal code,Borough,Neighborhood,Latitude,Longitude
0,M3A,North York,Parkwoods,43.753259,-79.329656
1,M4A,North York,Victoria Village,43.725882,-79.315572
2,M5A,Downtown Toronto,"Regent Park , Harbourfront",43.654260,-79.360636
3,M6A,North York,"Lawrence Manor , Lawrence Heights",43.718518,-79.464763
4,M7A,Downtown Toronto,"Queen's Park , Ontario Provincial Government",43.662301,-79.389494
5,M9A,Etobicoke,Islington Avenue,43.667856,-79.532242
6,M1B,Scarborough,"Malvern , Rouge",43.806686,-79.194353
7,M3B,North York,Don Mills,43.745906,-79.352188
8,M4B,East York,"Parkview Hill , Woodbine Gardens",43.706397,-79.309937
9,M5B,Downtown Toronto,"Garden District, Ryerson",43.657162,-79.378937

In [41]:
df_geo_merged.shape

(103, 5)